# Generated by Django 3.1.3 on 2020-11-26 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255, verbose_name='Institution name')),
                ('info_about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('img', models.ImageField(blank=True, null=True, upload_to='institutions', verbose_name='Image')),
                ('subscribers', models.ManyToManyField(to='social_profile.SocialProfile', verbose_name='Subscribers')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institution',
                'ordering': ('institution_name',),
            },
        ),
        migrations.CreateModel(
            name='LanguageWithLevelVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_profile.language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_profile.languagelevel')),
            ],
        ),
        migrations.CreateModel(
            name='RespondedVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_response', models.DateTimeField(auto_now_add=True, verbose_name='Date of response')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_profile.socialprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=255, verbose_name='Vacancy')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.IntegerField(choices=[(1, 'Opened'), (2, 'Completed'), (3, 'Blocked')], default=1, verbose_name='Status')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution', verbose_name='Institution')),
                ('languages', models.ManyToManyField(through='institution.LanguageWithLevelVacancy', to='social_profile.Language', verbose_name='Language')),
                ('responded', models.ManyToManyField(through='institution.RespondedVacancy', to='social_profile.SocialProfile', verbose_name='Responded')),
                ('skills', models.ManyToManyField(blank=True, to='social_profile.Skill', verbose_name='Skills')),
                ('who_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Who added')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ('vacancy',),
            },
        ),
        migrations.AddField(
            model_name='respondedvacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.vacancy'),
        ),
        migrations.AddField(
            model_name='languagewithlevelvacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.vacancy'),
        ),
    ]
