# Generated by Django 3.1.4 on 2020-12-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField(verbose_name='Path')),
            ],
            options={
                'verbose_name': 'File storage path',
                'verbose_name_plural': 'File storage path',
                'ordering': ('file_path',),
            },
        ),
    ]
