# Generated by Django 3.1.4 on 2020-12-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_server', '0002_auto_20201211_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileStorage',
        ),
    ]
